services: 
  database: 
    container_name: containerName
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: database_name
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
   
    

  